Improve TestMultiRenderTarget2 test Demo
jMonkeyEngine/jmonkeyengine pull request #1654
Opened 2021-11-15 06:22 UTC by JohnLKkk

Improve TestMultiRenderTarget2 test Demo

2021-11-17 19:01 UTC, stephengold commented
Thanks for creating this PR.

It needs some additional documentation. The class-level javadoc should say what the test does and how to tell whether the test is successful ("Displays 4 pictures, each showing a different render of a hovertank."). The pictures don't have descriptive names, so comments should explain how each one differs from the others. Also some explanation, in "MRTLighting.j3md", of what the resulting material does.

I also have some line-by-line review, which will appear separately.

2021-11-17 19:22 UTC, stephengold requested changes

2021-11-17 19:22 UTC, stephengold commented on jme3-examples/src/main/java/jme3test/post/TestMultiRenderTarget2.java
> + * @date 2021年11月7日10点18分
"date" is an unknown javadoc tag. Remove it.

2021-11-17 19:22 UTC, stephengold commented on jme3-examples/src/main/java/jme3test/post/TestMultiRenderTarget2.java
> + * Note that this example is only used to demonstrate the simple use of multi-target rendering. It is different from optimized deferred rendering.<br/>
The "br/" tag is not allowed in javadoc.

2021-11-17 19:22 UTC, stephengold commented on jme3-examples/src/main/java/jme3test/post/TestMultiRenderTarget2.java
> +    private Texture2D diffuseData, normalData, specularData, depthData;
Put each declaration on a separate line.

2021-11-17 19:22 UTC, stephengold commented on jme3-examples/src/main/java/jme3test/post/TestMultiRenderTarget2.java
>      private Picture display1, display2, display3, display4;
Put each declaration on a separate line, with a descriptive comment.

2021-11-17 19:22 UTC, stephengold commented on jme3-examples/src/main/java/jme3test/post/TestMultiRenderTarget2.java
> +        display1.move(0, 0, -1);
This statement is unnecessary. Please remove it.

2021-11-17 19:22 UTC, stephengold commented on jme3-examples/src/main/java/jme3test/post/TestMultiRenderTarget2.java
> +        // lights
This section adds 20 lights to the scene. Why?

2021-11-17 19:22 UTC, stephengold commented on jme3-examples/src/main/java/jme3test/post/TestMultiRenderTarget2.java
> +        Material tankMat = assetManager.loadMaterial("jme3test/post/tank.j3m");
What does "tankMat" do?

2021-11-17 19:22 UTC, stephengold commented on jme3-examples/src/main/java/jme3test/post/TestMultiRenderTarget2.java
> +        guiNode.updateGeometricState();
Explicit updating is not needed here. Delete it.

2021-11-17 19:22 UTC, stephengold commented on jme3-examples/src/main/resources/jme3test/post/MRTLighting.j3md
> +MaterialDef MRTLighting {
Add explanatory comments here.

2021-11-17 19:22 UTC, stephengold commented on jme3-examples/src/main/java/jme3test/post/TestMultiRenderTarget2.java
> +        initGBufferInfos();
What does the "G" in `initGBufferInfos()` stand for?

2021-11-17 19:28 UTC, stephengold commented
Also, when I run the new test, I get warnings. If possible, please modify the test to avoid these:
```text
Nov 17, 2021 11:16:02 AM com.jme3.material.plugins.J3MLoader readDefine
WARNING: In technique 'LightPass':
Define 'ATTENUATION' mapped to non-existent material parameter 'Attenuation', ignoring.
Nov 17, 2021 11:16:02 AM com.jme3.material.plugins.J3MLoader readDefine
WARNING: In technique 'LightPass':
Define 'HQ_ATTENUATION' mapped to non-existent material parameter 'HighQuality', ignoring.
```

2021-12-06 23:22 UTC, stephengold commented
@JohnLKkk are you still available to work on this?

2021-12-11 22:19 UTC, JohnLKkk commented
Sorry, I'm a bit busy this time, I will check the warning message here.

2021-12-12 08:12 UTC, JohnLKkk commented
> Sorry, I'm a bit busy this time, I will check the warning message here.

2023-10-06 00:37 UTC, closed without merging