NullPointerException in AnimLayer.update()
jMonkeyEngine/jmonkeyengine pull request #1730
Opened 2022-01-05 23:25 UTC by capdevon

java.lang.NullPointerException: Cannot invoke
"com.jme3.anim.tween.action.Action.setMask(com.jme3.anim.AnimationMask)"
because "this.currentAction" is null
        at com.jme3.anim.AnimLayer.update(AnimLayer.java:209)
        at com.jme3.anim.AnimComposer.controlUpdate(AnimComposer.java:391)
        at com.jme3.scene.control.AbstractControl.update(AbstractControl.java:118)
        at com.jme3.scene.Spatial.runControlUpdate(Spatial.java:743)
        at com.jme3.scene.Spatial.updateLogicalState(Spatial.java:890)
        at com.jme3.scene.Node.updateLogicalState(Node.java:228)
        at com.jme3.scene.Node.updateLogicalState(Node.java:239)

2022-01-06 05:07 UTC, Ali-RS commented
Looks good to me, thank you @capdevon! 

This will be merged in 24H unless there is more to discuss.

2022-01-06 21:56 UTC, stephengold commented
Does the choice of variable name count as substantial discussion?

2022-01-07 06:09 UTC, Ali-RS commented
>Does the choice of variable name count as substantial discussion?

Yes I think so.

@stephengold please continue the discussion about variable name, I will delay the merge until then. Thanks!

2022-01-07 06:21 UTC, stephengold requested changes

2022-01-07 06:21 UTC, stephengold commented on jme3-core/src/main/java/com/jme3/anim/AnimLayer.java
> +        Action runningAction = currentAction;
@capdevon what do you think?

2022-01-07 09:17 UTC, capdevon commented on jme3-core/src/main/java/com/jme3/anim/AnimLayer.java
> +        Action runningAction = currentAction;
ok that's fine for me

2022-01-07 17:43 UTC, stephengold approved these changes

2022-01-07 17:44 UTC, merged

2022-01-07 17:45 UTC, stephengold commented
Thanks @capdevon and @Ali-RS !

2022-01-10 21:46 UTC, stephengold commented
Confirmed fixed in v3.5.0-beta6 ... https://hub.jmonkeyengine.org/t/v3-5-0-beta-testing/45209/26