SceneGraphIterator
jMonkeyEngine/jmonkeyengine pull request #2080
Opened 2023-10-06 13:42 UTC by codex128

Small quality-of-life improvement. :)

This pull request adds a class that iterates over the scene graph with the depth-first approach. The advantage to using this over the standard scene traversal is being able to use enhanced for-loops, which allow for functionality lambdas are not capable of. I have found this to be very useful for processing scenes at runtime.

Basic usage:
```java
Spatial main = ...
for (Spatial spatial : new SceneGraphIterator(main)) {
    // ...
}
```
The iterator has a couple useful methods:
```java
// makes the iterator not iterate over the children of the current spatial
iterator.ignoreChildren();

// gets the current depth (distance from the current spatial to the main spatial)
iterator.getDepth();
```
Example: count geometries
```java
int total = 0;
Spatial gameScene = rootNode.getChild("game-scene");
for (Spatial spatial : new SceneGraphIterator(gameScene)) {
    if (spatial instanceof Geometry) {
        total++;
    }
}
```
Example: selective material replacement
```java
SceneGraphIterator iterator = new SceneGraphIterator(rootNode);
Material replace = assetManager.loadMaterial("Material/MyMaterial.j3m");
for (Spatial spatial : iterator) {
    // any geometry under "house1" should not use the replacement material
    if ("house1".equals(spatial.getName())) {
        iterator.ignoreChildren();
        continue;
    }
    if (spatial instanceof Geometry) {
        ((Geometry)spatial).setMaterial(replace);
    }
}
```

2023-10-12 07:06 UTC, stephengold requested changes

2023-10-12 07:06 UTC, stephengold commented on jme3-examples/src/main/java/jme3test/scene/TestSceneIteration.java
> +    private String constructTabs(int n) {
A blank line should appear between consecutive methods in a class.

2023-10-15 01:15 UTC, stephengold approved these changes

2023-10-15 01:16 UTC, stephengold commented
Unless there's further substantive discussion, I plan to integrate this PR in about 48 hours.

2023-10-17 06:14 UTC, merged

2023-10-17 06:15 UTC, stephengold commented
GitHub wouldn't let me rebase, so I integrated using "squash and merge".

2023-10-17 06:27 UTC, stephengold commented
Thanks for another good contribution to JMonkeyEngine, @codex128 !

2023-10-17 11:50 UTC, codex128 commented
You're welcome. Glad to do it!