Fixes Issue #2083
jMonkeyEngine/jmonkeyengine pull request #2086
Opened 2023-10-08 23:52 UTC by codex128

Fixes enabling of vertex colors in the gltf loader as described in #2083.

2023-10-09 05:18 UTC, stephengold requested changes

2023-10-09 05:18 UTC, stephengold commented on jme3-examples/src/main/java/jme3test/asset/TestIssue2083.java
> +/*
Please include the standard JME license header.

2023-10-09 05:18 UTC, stephengold commented on jme3-examples/src/main/java/jme3test/asset/TestIssue2083.java
> +    public static void main(String[] args) {
Public method should have javadoc

2023-10-09 05:18 UTC, stephengold commented on jme3-examples/src/main/java/jme3test/asset/TestIssue2083.java
> + * Vertex colors on gltf models was not being enabled.
Test documentation should indicate how to determine whether the test passed or failed.

2023-10-09 12:02 UTC, codex128 commented on jme3-examples/src/main/java/jme3test/asset/TestIssue2083.java
> +/*
I copied the header from another class. What should I put for the date on the copyright?

2023-10-09 15:57 UTC, stephengold commented on jme3-examples/src/main/java/jme3test/asset/TestIssue2083.java
> +/*
Assuming this is newly-written code, "2023" will do fine for the copyright date.

2023-10-12 07:40 UTC, stephengold commented on jme3-examples/src/main/java/jme3test/asset/TestIssue2083.java
> +     * @param args
@param tag shouldn't appear with an empty description.

2023-10-15 01:10 UTC, stephengold approved these changes

2023-10-15 01:11 UTC, stephengold commented
Thank you, @codex128 !

Unless there's additional substantive feedback, I plan to integrate this PR in about 48 hours.

2023-10-16 15:59 UTC, stephengold commented
Ugh! Huge merge conflict with PR #2104. Could someone resolve it for me?

2023-10-16 16:02 UTC, riccardobl commented
> Ugh! Huge merge conflict with PR #2104. Could someone resolve it for me?

Working on it

2023-10-16 16:18 UTC, riccardobl commented
> Ugh! Huge merge conflict with PR #2104. Could someone resolve it for me?

Resolved and added a test.

2023-10-17 06:17 UTC, merged

2023-10-17 06:18 UTC, stephengold commented
Thank you for your contributions, @codex128 and @riccardobl .

2024-05-26 16:52 UTC, stephengold commented
FoxCC has reported a possible issue with e440f31:  https://hub.jmonkeyengine.org/t/jmonkeyengine-v3-7-0-beta1-release/47653/40