J3o Version Update to 3
jMonkeyEngine/jmonkeyengine pull request #2093
Opened 2023-10-11 18:22 UTC by codex128

Updates the J3o version from 2 to 3, and adds "jme-" prefix to userdata maps, lists, and arrays to fix #2068 xml export issue.

2023-10-11 19:14 UTC, riccardobl commented
I think the prefix should be added and removed inside

jme3-plugins/src/xml/java/com/jme3/export/xml/DOMOutputCapsule.java
jme3-plugins/src/xml/java/com/jme3/export/xml/DOMInputCapsule.java

since it fixes a limitation that is specific to xml specs

2023-10-13 22:29 UTC, riccardobl commented
Can you bump the format to 3 as you did in the first draft and enable the prefix only for formats >=3 ? So that we can keep backward compatibility for already exported xml.

2023-10-13 22:45 UTC, codex128 commented
Sorry, I should have thought of that before. :P

2023-10-14 09:04 UTC, riccardobl requested changes

2023-10-14 09:04 UTC, riccardobl commented on jme3-plugins/src/xml/java/com/jme3/export/xml/DOMInputCapsule.java
> +        String version = XMLUtils.getAttribute(currentElem, "format_version");
This should be always unprefixed for backward compatibility

2023-10-14 09:04 UTC, riccardobl commented on jme3-plugins/src/xml/java/com/jme3/export/xml/XMLUtils.java
> +        if (FormatVersion.VERSION >= 3) {
To support old files, the check should be against `importer.formatVersion`  that is the version of the imported file, and not `FormatVersion.VERSION` that is the current supported version.

2023-10-14 12:45 UTC, riccardobl approved these changes

2023-10-14 12:47 UTC, riccardobl commented
Looks fine now, thank you!

2023-10-14 13:06 UTC, riccardobl requested changes

2023-10-14 13:06 UTC, riccardobl commented on jme3-plugins/src/xml/java/com/jme3/export/xml/DOMOutputCapsule.java
> +            XMLUtils.setAttribute(ret, "format_version", Integer.toString(FormatVersion.VERSION));
This should not be prefixed, same as in the input capsule

2023-10-14 13:07 UTC, riccardobl commented
Sorry, i did one last review before the merge and i've found there is still one last issue, the format_version is prefixed on the output capsule

2023-10-14 13:30 UTC, riccardobl approved these changes

2023-10-14 17:23 UTC, merged