Deprecate TangentBinormalGenerator
jMonkeyEngine/jmonkeyengine pull request #2144
Opened 2023-11-09 17:10 UTC by riccardobl

This PR deprecated TangentBinormalGenerator in favor of MikktspaceTangentGenerator that is the defacto standard.
The PR adds a bit more context to the comments in MikktspaceTangentGenerator and removes the part about it being experimental, since at this point it has been tested and patched enought to be considered out of the experimental stage.

2023-11-14 02:18 UTC, codex128 requested changes
Just a typo on a javadoc link needs fixing.

2023-11-14 02:18 UTC, codex128 commented on jme3-core/src/main/java/com/jme3/util/TangentBinormalGenerator.java
> + * @deprecated This is an outdated and non-standard method. Please use @{link MikktspaceTangentGenerator}
Change `@{link` to `{@link`.

2024-02-06 08:31 UTC, capdevon commented
Hi guys, what is the status of this PR ? Is it complete ?

2024-12-28 05:31 UTC, yaRnMcDonuts commented
> Hi guys, what is the status of this PR ? Is it complete ?

After reviewing the code, I would say it is complete and looks ready to be merged. I have also been using the MikktSpaceTangentGenerator extensively with a fairly wide variety of models in my own project and editor for at least 2 years now, so I am personally confident in its reliability.

I'd also like to try to merge this to get it into the 3.8 alpha release that will be out soon. That way we can get jme users testing these changes as early in the alpha / beta process as possible. 

But (since this PR has been sitting for a while) I will wait a few days before merging, in case @riccardobl has anything to add or wants to change anything before the PR is merged.

2024-12-31 02:41 UTC, yaRnMcDonuts approved these changes

2024-12-31 02:42 UTC, merged

2024-12-31 02:46 UTC, yaRnMcDonuts commented
I merged this PR so it will be in the first 3.8.0-alpha1 release in the next day or so.

There were many engine examples updated in this PR to use MikktspaceTangentGenerator and there will be a handful of test-cases that will need testing, so I think getting this into the alpha release asap is important.

I took a screenshot of every test-case / example that was changed in this PR, so that will hopefully make it easier for users to reference this list test all of these in rapid succession:

![image](https://github.com/user-attachments/assets/53425a05-2cdc-44fc-95db-1118dce254c5)